<?php

/**
 * @file
 * Display Livefyre comments.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\livefyre\LivefyreNodeView;

/**
 * Implements hook_node_view().
 */
function livefyre_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  $node_view = new LivefyreNodeView();
  $build += $node_view->view($entity, $view_mode);
}
