<?php


/**
 * Implementation of hook_menu
 */
function livefyre_menu() {
  return array(
      'admin/settings/livefyre' => array(
        'title' => 'Livefyre',
        'description' => t('Configure livefyre comments'),
        'access arguments' => array('administer livefyre comments'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('livefyre_admin_settings'),
        'file' => 'livefyre.admin.inc',
        ),
      );
}

/**
 * Implementation of hook_nodeapi
 */
function livefyre_nodeapi(&$node, $op, $teaser = NULL, $page = NULL) {
  switch ($op) {
    case 'view':
      $lf_node_types = variable_get('livefyre_node_types', array());
      $lf_disabled = variable_get('livefyre_disabled', TRUE);
      $lf_account_num = variable_get('livefyre_acct_num', '');
      $livefyre_supplied_js =  variable_get('livefyre_supplied_js', '');
      $custom_script_snippet =  variable_get('custom_script_snippet', '');
      $lf_free_version_check = variable_get('lf_free_version', 1);
      $free_version_html = "<!-- START: Livefyre Embed -->
<script type='text/javascript' src='$livefyre_supplied_js'></script>
<!--<style type='text/css'>#lf_message_tbl{height: 100px !important;}</style>-->
<script type='text/javascript'>
    var fyre = LF({
        site_id: $lf_account_num
    });
</script>
<!-- END: Livefyre Embed -->";
      if ($lf_disabled || empty($lf_account_num)) {
        return;
      }
      $show_lf = count(array_keys($lf_node_types, $node->type))
                 && (!$teaser && $page && isset($node->body))
                 && (variable_get('livefyre_location', 'content_area') == 'content_area');
                 echo $show_lf;
      if ($show_lf) {
        $node->content['livefyre'] = array(
          '#value' => theme('livefyre_comments', $livefyre_supplied_js, $lf_account_num, $custom_script_snippet, $free_version_html, $lf_free_version_check),
          '#weight' => variable_get('livefyre_weight', 50),
          );
      }
      break;
    default:
      break;
  }
}

/**
 * Implementation of hook_perm
 */
function livefyre_perm() {
  return array('administer livefyre comments');
}

/**
 * Implementation of hook_block
 */
function livefyre_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      return array(
          'livefyre_comments' => array(
            'info'  => t('Livefyre Comments'),
            'cache' => BLOCK_NO_CACHE),
          );
      break;
    case 'view':
      switch ($delta) {
        case 'livefyre_comments':
          $lf_disabled = variable_get('livefyre_disabled', TRUE);
          $lf_location = variable_get('livefyre_location', 'content_area');
          
          if (!$lf_disabled && $lf_location == 'block') {
          $lf_account_num = variable_get('livefyre_acct_num', '');
          $livefyre_supplied_js =  variable_get('livefyre_supplied_js', '');
          $custom_script_snippet =  variable_get('custom_script_snippet', '');
          $lf_free_version_check = variable_get('lf_free_version', 1);
          $free_version_html = "<!-- START: Livefyre Embed -->
<style type='text/css'>#lf_message_tbl{height: 100px !important;}</style>
<script type='text/javascript' src='$livefyre_supplied_js'></script>
<script type='text/javascript'>
    var fyre = LF({
        site_id: $lf_account_num
    });
</script>
<!-- END: Livefyre Embed -->";
          return array(
                'content' => theme('livefyre_comments', $livefyre_supplied_js, $lf_account_num, $custom_script_snippet, $free_version_html, $lf_free_version_check),
            );
          }
          break;
        default:
          break;
      }
      break;
    default:
      break;
  }
}

/**
 * Implementation of hook_theme
 */
function livefyre_theme() {
  return array(
  'livefyre_comments' => array(
    'arguments' => array(
      'livefyre_supplied_js' => NULL,
      'lf_account_num' => NULL,
      'custom_script_snippet' => NULL,
      'free_version_html' => NULL,
      'lf_free_version_check' => NULL,
      ),
    )
  );
}

function theme_livefyre_comments($livefyre_supplied_js, $lf_account_num, $custom_script_snippet, $free_version_html, $lf_free_version_check) {
  //echo '$lf_free_version_check ' . $lf_free_version_check;
  // Livefyres textfield for comments was getting a ridiculous amount of height.
  // Adding in the '!important' bit for now.
 if ($lf_free_version_check !== 1) {
  return "$custom_script_snippet";
  }
  else {
    return "$free_version_html";
  }
}