livefyre.settings:
  type: config_object
  mapping:
    livefyre_disabled:
      type: boolean
    livefyre_acct_num:
      type: string
    livefyre_supplied_js:
      type: string
    livefyre_parent_div:
      type: string
    livefyre_custom_instantiate_lf:
      type: string
    livefyre_custom_script_snippet:
      type: string
    livefyre_node_types:
      type: sequence
      sequence:
        type: string
    livefyre_location:
      type: string
    livefyre_weight:
      type: integer
