livefyre.settings:
  type: config_object
  mapping:
    disabled:
      type: boolean
    site_id:
      type: string
    site_key:
      type: string
    network:
      type: string
    network_key:
      type: string
    supplied_js:
      type: string
    parent_div:
      type: string
    custom_instantiate_lf:
      type: string
    custom_script_snippet:
      type: string
    node_types:
      type: sequence
      sequence:
        type: string
    location:
      type: string
    weight:
      type: integer
    network:
      type: string
